# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=264)),
                ('post_description', models.TextField()),
                ('post_photo', models.FileField(upload_to='images')),
                ('post_create_date', models.DateTimeField(auto_now=True)),
                ('post_authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.MyUser')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Post_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.MyUser')),
                ('comments_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'verbose_name': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='likes',
            name='like_to_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post'),
        ),
    ]
